### PR TITLE
Remove named import transformer

### PR DESCRIPTION
**Pull request by FrederikBolding**
The named import transformer was added to solve a problem when importing from TypeScript, e.g. 
```
import { createSourceFile } from "typescript";
```
causing an error along the lines of
```
SyntaxError: Named export 'createSourceFile' not found. The requested module 'typescript' is a CommonJS module, which may not support all module.exports as named exports.
```

It turns out that this problem was solved upstream in `typescript` and that our renaming transformer causes problems in Webpack, therefore I propose we stop using the named import transformer entirely.

### CODE REVIEW

**Comment by mcmire** [comment]
Out of interest which version of TypeScript was this added to?

**Comment by FrederikBolding** [comment]
> Out of interest which version of TypeScript was this added to?

Fixed in the latest beta version: [5.5.0-beta](https://www.npmjs.com/package/typescript/v/5.5.0-beta)

**Comment by Mrtenz** [comment]
This is not an issue with just TypeScript to be clear. Node.js' CJS import detection in ESM is quite limited, and something like this causes the same issue:

```ts
const someAliasForExports = module.exports;

someAliasForExports.foo = 'bar';
```

When importing like this:

```ts
// import { foo } from './foo.cjs';
//         ^^^
// SyntaxError: Named export 'foo' not found. The requested module './foo.cjs' is a CommonJS module, which
// may not support all module.exports as named exports.
import { foo } from './foo.cjs';
```

While this works:

```ts
import defaultImport from './foo.cjs';
defaultImport.foo;
```

**Comment by Mrtenz** [comment]
We may need to implement [`cjs-module-lexer`](https://github.com/nodejs/cjs-module-lexer) to detect if something is importable or not.

**Pull request closed without merging**
